### ISSUE TITLE
Method not found: 'Void SharpAstrology.DataModels.PlanetPosition.set_Longitude(Double)

### ISSUE THREAD

**Issue by QuadMan** [CReizner/SharpAstrology.Base#1]
Hello!
Trying to run examples and got this error:
Method not found: **'Void SharpAstrology.DataModels.PlanetPosition.set_Longitude(Double)**

on line: 
**_`var chart = new AstrologyChart(date, eph);`_**

How can I fix it?

Code is below:
`using SharpAstrology.DataModels;
using SharpAstrology.Enums;
using SharpAstrology.Ephemerides;
using SharpAstrology.Interfaces;

//var date = new DateTime(1981, 10, 27, 9, 45, 0, DateTimeKind.Utc);
var date = new DateTime(1988, 9, 4, 1, 15, 0, DateTimeKind.Utc);
//using var eph = new SwissEphemeridesService(ephType: EphType.Moshier).CreateContext();

var ephemeridesService = new SwissEphemeridesService(ephType: EphType.Moshier);
using IEphemerides eph = ephemeridesService.CreateContext();

// Create chart
var chart = new AstrologyChart(date, eph);

// Houses
Console.WriteLine(chart.HousePositions is null ? "No houses available" : "Houses available");
// Output: No houses available

// Planet positions
foreach (var planet in chart.SupportedObjects)
{
    Console.WriteLine($"{planet} - {Math.Round(chart.PositionOf(planet).Longitude, 2)}° in sign {chart.SignOf(planet)} and constellation {chart.ConstellationOf(planet)} is {chart.MotionOf(planet)} moving.");
}
// Output:
// Sun - 161,73° in sign Virgo and constellation Leo is Forward moving.
// Moon - 82,41° in sign Gemini and constellation Taurus is Forward moving.
// Mercury - 185,87° in sign Libra and constellation Virgo is Forward moving.
// Venus - 116,41° in sign Cancer and constellation Cancer is Forward moving.
// Mars - 10,96° in sign Aries and constellation Pisces is Retrograde moving.
// Jupiter - 65,44° in sign Gemini and constellation Taurus is Forward moving.
// Saturn - 265,95° in sign Sagittarius and constellation Sagittarius is Forward moving.
// NorthNode - 344,1° in sign Pisces and constellation Aquarius is Retrograde moving.
// SouthNode - 164,1° in sign Virgo and constellation Leo is Retrograde moving.
// Uranus - 267,04° in sign Sagittarius and constellation Sagittarius is Retrograde moving.
// Neptune - 277,48° in sign Capricorn and constellation Sagittarius is Retrograde moving.
// Pluto - 220,35° in sign Scorpio and constellation Libra is Forward moving.

// Angles between planets (-180°,180°].
Console.WriteLine(chart.AngleOf(Planets.Sun, Planets.Mars));
Console.WriteLine(chart.AngleOf(Planets.Mars, Planets.Sun));
// Output:
// 150,76609634460928
// -150,76609634460928`

**Comment by CReizner** [comment]
Hi, the issue is, that the SharpAstrology,SwissEph package is using the SharpAstrology.Base package below the version 0.9.0. Until than, the PlanetPosition class has only init setters and the AstrologyChart class is trying to set the longitude after initialization. So it is completely my fault. I will now set all SharpAstrology packages to the latest Base version. Thanks for commenting on this issue.

**Comment by QuadMan** [comment]
Hi!
I'm using fresh nuget packets - SharpAstrology.Base version 0.10.0 and SharpAStrology.SwissEph 0.2.1.

**Comment by CReizner** [comment]
Yes, but The SwissEph package in version 0.2.1 is still referencing to the Base version of 0.8.0 and this is a problem I will fix now. In a few minutes, you will find SharpAstrology.SwissEph version 0.2.2 in NuGet an I will block the older versions.
